name: Deploy Ionic React Vite to Elastic Beanstalk (Node 20 + Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Zip application for Elastic Beanstalk
        run: zip -r app.zip . -x "*.git*"

      - name: Generate timestamp for version label
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: twitter-clone-front
          environment_name: twitter-clone-front
          region: eu-north-1
          version_label: ${{ github.sha }}-${{ env.TIMESTAMP }}
          deployment_package: app.zip
